version: '3.8'

name: btc-rate

services:
  feature-coin:
    container_name: feature-coin
    depends_on:
      - rabbitmq
    build:
      context: src/.
      dockerfile: coin/Dockerfile
    volumes:
      - coinData:/app/coin/data
      - logs:/app/coin/logs
    ports:
      - "8080:8080"

#  feature-campaign:
#    container_name: feature-campaign
#    build:
#      context: src/.
#      dockerfile: campaign/Dockerfile
#    volumes:
#      - campaignData:/app/campaign/data
#      - logs:/app/campaign/logs
#    ports:
#      - "8081:8081"
#    environment:
#      - COIN_HOST=feature-coin:8080
#      - COIN_SCHEMA=http
#      - SENDGRID_KEY=your_key
#      - SENDGRID_SENDER_EMAIL=your_email
#      - SENDGRID_SENDER_NAME=your_name

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/

volumes:
  coinData:
  campaignData:
  logs:
  rabbitmq:
